### ISSUE TITLE
코드 수정 요청 사항

### ISSUE THREAD

**Issue by snoopspy** [choikongji/pcap-test#1]
https://github.com/choikongji/pcap-test/commit/25fdb237ac76a3d02a10c8d80f6c076bc6b9daa8#r38443924

**Comment by choikongji** [comment]
done in
https://github.com/choikongji/pcap-test/commit/2c5740e7d8ca881a5353f9d3c65b0fa048c16804?diff=unified

**Comment by snoopspy** [comment]
수고하셨습니다.
